---
title: "R Notebook"
output: html_notebook
---

```{r}
data <- data.frame(x1=c(3,6,5,10),x2=c(10,12,14,9))
n <- 4
p <- 2
xbar = colMeans(data)
xbar
col <- c(6,11)
xbarmod <- xbar-col
s = cov(data)
s
sinv <- solve(s)
sinv
T2 <- n%*%t(xbarmod)%*%sinv%*%xbarmod
print(paste0("nilai T^2 = ", round(T2,3)))
T2
kritis <- (n-1)*p/(n-p)
dff <- kritis * qf(.95,df1=p,df2=n-p)
print(paste0("daerah kritisnya = ", round(dff,3)))
if (T2 > dff) {
print(paste0("Tolak H0, karena T^2 > titik kritis"))
} else {
print(paste0("Gagal Tolak H0 karena T^2 < titik kritis"))
}
```

```{r}
data2 <- data.frame(y1=c(51,27,37,42,27,43,41,38,36,26,29),y2=c(36,20,22,36,18,32,22,21,23,31,20),y3=c(50,26,41,32,33,43,36,31,27,31,25),y4=c(35,17,37,34,14,35,25,20,25,32,26),y5=c(42,27,30,27,29,40,38,16,28,36,25))
n2 <- nrow(data2)
p2 <- ncol(data2)
xbar2 = colMeans(data2)
xbar2
col2 <- c(30,25,40,25,30)
xbarmod2 <- xbar2-col2
s2 = cov(data2)
s2
sinv2 <- solve(s2)
sinv2
T22 <- n2%*%t(xbarmod2)%*%sinv2%*%xbarmod2
print(paste0("nilai T^2 = ", round(T22,3)))
kritis2 <- (n2-1)*p2/(n2-p2)
dff2 <- kritis2 * qf(.95,df1=p2,df2=n2-p2)
print(paste0("daerah kritisnya = ", round(dff2,3)))
if (T22 > dff2) {
print(paste0("Tolak H0, karena T^2 > titik kritis"))
} else {
print(paste0("Gagal Tolak H0 karena T^2 < titik kritis"))
}
```
```{r}
for(i in 1:5){
  t = (xbar2[i] - col2[i])/(s2[i,i]/sqrt(10))
  print(t)
}
```



```{r}
library(car)
alpha<-0.05
tconst2 <- sqrt((p2/n2)*((n2-1)/(n2-p2)) * qf(1-alpha,p2,n2-p2))
id <- c(4,5)
plot(ellipse(center=xbar2[id], shape=s2[id,id], radius=tconst2,draw=F),type="n", xlab="y4", ylab="y5")
lines(ellipse(center=xbar2[id], shape=s2[id,id], radius=tconst2,
lwd=3), xlab="y4", ylab="y5")
points(25,30,col="red", pch=16)
text(25.5,30.5,expression(mu[0]))
text(xbar2[4]+0.5,xbar2[5],expression(bar(x)))
```

```{r}
T.ci <- function(mu, Sigma, n, avec=rep(1,length(mu)),
level=0.95){
p <- length(mu)
if(nrow(Sigma)!=p) stop("Need length(mu) == nrow(Sigma).")
if(ncol(Sigma)!=p) stop("Need length(mu) == ncol(Sigma).")
if(length(avec)!=p) stop("Need length(mu) == length(avec).")
if(level <=0 | level >= 1) stop("Need 0 < level < 1.")
cval <- qf(level, p, n-p) * p * (n-1) / (n-p)
zhat <- crossprod(avec, mu)
zvar <- crossprod(avec, Sigma %*% avec) / n
const <- sqrt(cval * zvar)
c(lower = zhat - const, upper = zhat + const)
}
T.ci(mu=xbar2, Sigma=s2, n=n2, avec=c(1,0,0,0,0))
T.ci(mu=xbar2, Sigma=s2, n=n2, avec=c(0,1,0,0,0))
T.ci(mu=xbar2, Sigma=s2, n=n2, avec=c(0,0,1,0,0))
T.ci(mu=xbar2, Sigma=s2, n=n2, avec=c(0,0,0,1,0))
T.ci(mu=xbar2, Sigma=s2, n=n2, avec=c(0,0,0,0,1))
```

```{r}
TCI <- tCI <- bon <- NULL
alpha1<-1-0.05
alpha2<-1-(0.05/2)
alpha3 <- 1 - 0.05/(2*4)
for(k in 1:5){
avec <- rep(0, 5)
avec[k] <- 1
TCI <- c(TCI, T.ci(xbar2, s2, n2, avec,level=alpha1))
tCI <- c(tCI,
xbar2[k] - sqrt(s2[k,k]/n2) * qt(alpha2, df=n2-1),
xbar2[k] + sqrt(s2[k,k]/n2) * qt(alpha2, df=n2-1))
bon <- c(bon,
xbar2[k] - sqrt(s2[k,k]/n2) * qt(alpha3, df=n2-1),
xbar2[k] + sqrt(s2[k,k]/n2) * qt(alpha3, df=n2-1))
}
rtab <- rbind(TCI, tCI, bon)
round(rtab, 2)
```


```{r}
datap <- data.frame(ipm=c(70.09,58.03,71.69,68.83,67.66,72.19,56.31,48.37,74.19,61.53,58.15,50.55,49.37,45.44,49.50,63.63,66.40,64.94,62.30,51.78,31.55,47.86,47.57,48.34,43.04,54.84,47.79,49.46,79.94),laju=c(0.07,-2.10,-4.57,1.04,-2.16,-4.63,2.50,-1.11,15.62,-0.25,1.01,4.09,3.48,2.87,5.03,4.38,2.49,-0.28,3.26,4.77,4.49,5.82,4.40,5.27,2.66,3.23,2.01,3.56,-0.51))
datap
```

```{r}
n<-dim(datap)[1]
p<-dim(datap)[2]
S.inv<- solve(cov(datap))
xbar<-apply(datap,2,mean)
satu<-rep(1,29)
D<-datap-satu %*% t(xbar)
distance2<-matrix(rep(0,n),n,1)
D <- data.matrix(D)
for(i in 1:n){
  distance2[i,] <- t(D[i,]) %*% S.inv %*% D[i,]
  
}
round(distance2,digits = 3)
Dist.order<-sort(distance2)
round(Dist.order, digits=3)
Q<-matrix(rep(0,n),n,1)
for (j in 1:n ){
Q[j,]=qchisq((j-0.5)/n,df=p)}
round(Q,digits = 3)
library(car)
scatterplot(Q,Dist.order, grid=FALSE,regLine=FALSE,smooth=FALSE,
boxplot="",pch=16,xlab= expression(paste(chi[p]^2, " quantile")),
ylab="ordered distance")
abline(a=0,b=1, col="red")
```

```{r}
library(MVN)
library(RVAideMemoire)
mvn(datap[,1:2], mvnTest = "mardia",alpha = 0.05)
mvn(datap[,1:2], mvnTest = "hz",alpha = 0.05)
mvn(datap[,1:2], mvnTest = "royston",alpha = 0.05)
mvn(datap[,1:2], mvnTest = "dh",alpha = 0.05)
mshapiro.test(datap[,1:2])
```

```{r}
outlier <- mvn(datap[,1:2],multivariateOutlierMethod = "adj",
showNewData = TRUE,showOutliers = TRUE)
outlier
```

```{r}
datapbaru <- datap[-c(9, 21, 29),]
mvn(datapbaru[,1:2], mvnTest = "mardia",alpha = 0.05)
mvn(datapbaru[,1:2], mvnTest = "hz",alpha = 0.05)
mvn(datapbaru[,1:2], mvnTest = "royston",alpha = 0.05)
mvn(datapbaru[,1:2], mvnTest = "dh",alpha = 0.05)
mshapiro.test(datapbaru[,1:2])
```

```{r}
n <- nrow(datapbaru)
p <- ncol(datapbaru)
xbar = colMeans(datapbaru)
col <- c(63.94,4.7)
xbarmod <- xbar-col
s = cov(datapbaru)
sinv <- solve(s)
T2 <- n%*%t(xbarmod)%*%sinv%*%xbarmod
print(paste0("nilai T^2 = ", round(T2,3)))
kritis2 <- (n-1)*p/(n-p)
dff <- kritis * qf(.95,df1=p,df2=n-p)
print(paste0("daerah kritisnya = ", round(dff,3)))
if (T2 > dff) {
print(paste0("Tolak H0, karena T^2 > titik kritis"))
} else {
print(paste0("Gagal Tolak H0 karena T^2 < titik kritis"))
}
```

```{r}
library(car)
alpha<-0.05
tconst <- sqrt((p/n)*((n-1)/(n-p)) * qf(1-alpha,p,n-p))
id <- c(1,2)
plot(ellipse(center=xbar[id], shape=s[id,id], radius=tconst,draw=F),type="n", xlab="ipm", ylab="laju",xlim=c(50,70), ylim=c(0,5))
lines(ellipse(center=xbar[id], shape=s[id,id], radius=tconst,
lwd=3), xlab="ipm", ylab="laju")
points(63.94,4.7,col="red", pch=16)
text(63.94,4.7,expression(mu[0]))
text(xbar[1]+0.5,xbar[2],expression(bar(x)))
```

```{r}
TCI <- tCI <- bon <- NULL
alpha1<-1-0.05
alpha2<-1-(0.05/2)
alpha3 <- 1 - 0.05/(2*4)
for(k in 1:2){
avec <- rep(0, 2)
avec[k] <- 1
TCI <- c(TCI, T.ci(xbar, s, n, avec,level=alpha1))
tCI <- c(tCI,
xbar[k] - sqrt(s[k,k]/n) * qt(alpha2, df=n-1),
xbar[k] + sqrt(s[k,k]/n) * qt(alpha2, df=n-1))
bon <- c(bon,
xbar[k] - sqrt(s[k,k]/n) * qt(alpha3, df=n-1),
xbar[k] + sqrt(s[k,k]/n) * qt(alpha3, df=n-1))
}
rtab <- rbind(TCI, tCI, bon)
round(rtab, 2)
```

```{r}
qt(1-(0.05/2),10)
```

