---
title: "R Notebook"
output: html_notebook
---


```{r}
library(expm)
R11 <- matrix(c(1,0.615,0.615,1),2,2,byrow=TRUE)
R12 <- matrix(c(-0.111,-0.266,-0.195,-0.085),2,2,byrow=TRUE)
R21 <- matrix(c(-0.111,-0.195,-0.266,-0.085),2,2,byrow=TRUE)
R22 <- matrix(c(1,0.269,0.269,1),2,2,byrow=TRUE)
p <- 2
q <- 2
min.pq <- min(p,q)

```

```{r}
R11.sqrt.inv <- solve(sqrtm(R11))
R22.sqrt.inv <- solve(sqrtm(R22))

M1 <- R11.sqrt.inv%*%R12%*%solve(R22)%*%R21%*%R11.sqrt.inv
M2 <- R22.sqrt.inv%*%R21%*%solve(R11)%*%R12%*%R22.sqrt.inv

eig.M1 <- eigen(M1) # vektor eigennya disebut e
eig.M2 <- eigen(M2) # vektor eigennya disebut f
```

```{r}
(rho <- sqrt(eig.M2$values)[1:2])
rho
```

```{r}
a <- R11.sqrt.inv %*% eig.M1$vectors[,1:min.pq]
dimnames(a) <- list(c("X1","X2"), c("U1","U2"))
a
```

```{r}
b <- R22.sqrt.inv %*% eig.M2$vectors[,1:min.pq]
dimnames(b) <- list(c("Y1","Y2"), c("V1","V2"))
b
```

```{r}
R11 %*% a # Korelasi X dengan U
R22 %*% b # Korelasi Y dengan V

R12 %*% b # Korelasi X dengan V
R21 %*% a # Korelasi Y dengan U
```


#10.11

Matriks kovarians
```{r}
xbar <- matrix(c(0.0054,0.0048,0.0057),3,1)
ybar <- matrix(c(0.0063,0.0037),2,1)
R11 <- matrix(c(1,0.577,0.509,0.577,1,0.599,0.509,0.599,1),3,3,byrow=TRUE)
R12 <- matrix(c(0.387,0.462,0.389,0.322,0.436,0.426),3,2,byrow=TRUE)
R21 <- t(R12)
R22 <- matrix(c(1,0.523,0.523,1),2,2,byrow=TRUE)

p <- 3
q <- 2
min.pq <- min(p,q)
```

Eigen
```{r}
# Function untuk mencari akar invers matriks
sqrt_inv <- function(M) {
  eig <- eigen(M)
  result <- 1/sqrt(eig$values[1]) * eig$vectors[,1] %*% t(eig$vectors[,1])
  for (i in 2:ncol(M)) {
    result <- result + 1/sqrt(eig$values[i]) * eig$vectors[,i] %*% t(eig$vectors[,i])
  }
  result
}

R11.sqrt.inv <- sqrt_inv(R11)
R22.sqrt.inv <- sqrt_inv(R22)

# Cara lain
library(expm)
R11.sqrt.inv <- solve(sqrtm(R11))
R22.sqrt.inv <- solve(sqrtm(R22))

M1 <- R11.sqrt.inv%*%R12%*%solve(R22)%*%R21%*%R11.sqrt.inv
M2 <- R22.sqrt.inv%*%R21%*%solve(R11)%*%R12%*%R22.sqrt.inv

eig.M1 <- eigen(M1) # vektor eigennya disebut e
eig.M2 <- eigen(M2) # vektor eigennya disebut f
```

Korelasi Kanonik
```{r}
sqrt(eig.M1$values)[1:min.pq]
(rho <- sqrt(eig.M2$values)[1:min.pq])
```

Koefisien dari Variat Kanonik U
```{r}
a <- R11.sqrt.inv %*% eig.M1$vectors[,1:min.pq]
dimnames(a) <- list(c("X1","X2","X3"), c("U1","U2"))
a
```

Koefisien dari Variat Kanonik V
```{r}
b <- R22.sqrt.inv %*% eig.M2$vectors[,1:min.pq]
dimnames(b) <- list(c("Y1","Y2"), c("V1","V2"))
b
```

Korelasi
```{r}
R11 %*% a # Korelasi X dengan U
R22 %*% b # Korelasi Y dengan V

R12 %*% b # Korelasi X dengan V
R21 %*% a # Korelasi Y dengan U
```

#11.8
```{r}
library(readxl)
data8 <- read_excel("C:/Users/lili/Downloads/datatugas12.xlsx",sheet="Sheet1")
data8
```

```{r}
data8 <- as.data.frame(scale(data8))
col1 <- 1:2
col2 <- 3:5
data81 <- data8[,col1]
data82 <- data8[,col2]

p <- ncol(data81)
q <- ncol(data82)
n <- nrow(data8)
min.pq <- min(p,q)
```


```{r}
library(GGally)
ggpairs(data81)
ggpairs(data82)
```

```{r}
library(CCA)
correl<-matcor(data81, data82)
correl
img.matcor(correl,type=2)
```
```{r}
library(CCA)
cc2 <- cc(data81, data82)

(rho <- cc2$cor) # Korelasi Kanonik
```
```{r}
library(CCP)
p.asym(rho, n, p, q, tstat = "Wilks")
p.asym(rho, n, p, q, tstat = "Hotelling")
p.asym(rho, n, p, q, tstat = "Pillai")
p.asym(rho, n, p, q, tstat = "Roy")
```

```{r}
V11.sqrt <- diag(sqrt(diag(cov(data81))))
V22.sqrt <- diag(sqrt(diag(cov(data82))))

V11.sqrt %*% cc2$xcoef
V22.sqrt %*% cc2$ycoef
```



#11.9
```{r}
library(readxl)
data9 <- read_excel("C:/Users/lili/Downloads/datatugas12.xlsx",sheet="Sheet2")
data9
```

```{r}
data9 <- as.data.frame(scale(data9))
col1 <- 1:2
col2 <- 3:4
data91 <- data9[,col1]
data92 <- data9[,col2]

p <- ncol(data91)
q <- ncol(data92)
n <- nrow(data9)
min.pq <- min(p,q)
```

```{r}
library(GGally)
ggpairs(data91)
ggpairs(data92)
```

```{r}
library(CCA)
correl<-matcor(data91, data92)
correl
img.matcor(correl,type=2)
```

```{r}
library(CCA)
cc2 <- cc(data91, data92)

(rho <- cc2$cor) # Korelasi Kanonik
```

```{r}
library(CCP)
p.asym(rho, n, p, q, tstat = "Wilks")
p.asym(rho, n, p, q, tstat = "Hotelling")
p.asym(rho, n, p, q, tstat = "Pillai")
p.asym(rho, n, p, q, tstat = "Roy")
```

```{r}
V11.sqrt <- diag(sqrt(diag(cov(data91))))
V22.sqrt <- diag(sqrt(diag(cov(data92))))

V11.sqrt %*% cc2$xcoef
V22.sqrt %*% cc2$ycoef
```


