---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readxl)
library(DescTools)
library(asbio)
datakuis2 <- read_excel("C:/Users/lili/Downloads/datadata.xlsx")
datakuis2
```

```{r}
ybar <- colMeans(datakuis2)
a1=as.matrix(datakuis2[1:11,1:3],nrow=11,ncol=3)
a2=as.matrix(datakuis2[1:11,4:6],nrow=11,ncol=3)
colnames(a2)=c("x12","x22","x32")
gabung=rbind(a1,a2)
emosi=factor(c(rep(1,11),rep(2,11)))
gabung
mshapiro_test(datakuis2[,1])
mshapiro_test(datakuis2[,2])
mshapiro_test(datakuis2[,3])
mshapiro_test(datakuis2[,4])
mshapiro_test(datakuis2[,5])
mshapiro_test(datakuis2[,6])
Kullback(gabung,emosi)
```

```{r}
HotellingsT2Test(gabung~emosi)
```


```{r}
ybar1 <- colMeans(datakuis2[1:11,1:3])
ybar2 <- colMeans(datakuis2[1:11,4:6])
ybar1
ybar2
s1 <- cov(datakuis2[1:11,1:3])
s2 <- cov(datakuis2[1:11,4:6])
s1
s2
n1 <- 11
n2 <- 11
p <- 3
W <- (n1-1)*s1 + (n2-1)*s2
Sp <- W/(n1+n2-2)
Sp
diff <- ybar1-ybar2
p <- length(diff)
T2 <- (n1*n2/(n1+n2))*t(diff)%*%solve(Sp)%*%diff
solve(Sp)
p
diff
T2
```


```{r}
n1 <- 11
n2 <- 11
p <- 3
Fkrit <- ((n1+n2-2)*p/(n1+n2-p-1))*qf(0.95,p,n1+n2-p-1)
Fkrit
```

```{r}
for(i in 1:p){
    lower <- (ybar1[i]-ybar2[i])-sqrt(Fkrit)*sqrt((1/n1+1/n2)*Sp[i,i])
    upper <- (ybar1[i]-ybar2[i])+sqrt(Fkrit)*sqrt((1/n1+1/n2)*Sp[i,i])
    print(paste0(round(lower,3)," <<>> ",round(upper,3)))
}
```

