---
title: "R Notebook"
output: html_notebook
---


```{r}
A <- matrix(c(3,5,2,6,4,8,7,9,5),nrow=3)
B <- matrix(c(1,3,2,5,7,5,8,3,4),nrow=3)
A
print("======================")
B
```

```{r}
A*B
print("===================")
A%*%B
```

```{r}
crossprod(A,B)
```

```{r}
t(A)
print("==============")
t(B)
```

```{r}
solve(A)
print("================")
solve(B)
```

```{r}
det(A)
print("================")
det(B)
```

```{r}
diag(A)
print("==============")
diag(B)
```

```{r}
diag(c(2,4,3),3,3)
print("=================")
diag(2)
print("====================")
diag(diag(A))
```

```{r}
y1 <- c(35,35,40,10,6,20,35,35,35,30)
y2 <- c(3.5,4.9,30,2.8,2.7,2.8,4.6,10.9,8,1.6)
y3 <- c(2.8,7,4.38,3.21,2.73,2.81,2.88,2.9,3.28,3.2)
ydat <- data.frame(y1,y2,y3)
ybar1 <- apply(ydat,2,mean)
ybar <- colMeans(ydat)
ydat
n <- nrow(ydat)
print("=================")
ybar1
print("=================")
ybar
```

```{r}
d1 <- y1-ybar[1]
d2 <- y2-ybar[2]
d3 <- y3-ybar[3]
dmat <- matrix(c(d1,d2,d3),ncol=3)
dmat
print("===============")
dmatlain <- ydat-matrix(rep(ybar,10),nrow=10,byrow=TRUE)
dmat
```

```{r}
Sn <- 1/n*t(dmat)%*%dmat
Sn
```

```{r}
S <- n/(n-1)*Sn
S
print("===========")
cov(ydat)
```

```{r}
Ds <- diag(sqrt(diag(cov(ydat))))
Ds
```

```{r}
invDs <- solve(Ds)
invDs
```

```{r}
rmat <- invDs%*%cov(ydat)%*%invDs
rmat
```


