---
title: "R Notebook"
output: html_notebook
---

#independent
```{r}
ybar1 <- c(2.287,12.6,0.347)
ybar2 <- c(2.4,7.16,0.52)
s1 <- matrix(c(0.287,0.859,-0.087,0.859,3.839,-0.332,-0.087,-0.332,0.069),3,3,byrow=TRUE)
s2 <- matrix(c(0.418,-1.295,0.187,-1.295,10.351,-0.69,0.187,-0.69,0.097),3,3,byrow=TRUE)
n1 <- 20
n2 <- 20
W <- (n1-1)*s1 + (n2-1)*s2
Sp <- W/(n1+n2-2)
diff <- ybar1-ybar2
p <- length(diff)
T2 <- (n1*n2/(n1+n2))*t(diff)%*%solve(Sp)%*%diff
T2
Fkrit <- ((n1+n2-2)*p/(n1+n2-p-1))*qf(0.95,p,n1+n2-p-1)
Fkrit
```

```{r}
for(i in 1:p){
    lower <- (ybar1[i]-ybar2[i])-sqrt(Fkrit)*sqrt((1/n1+1/n2)*Sp[i,i])
    upper <- (ybar1[i]-ybar2[i])+sqrt(Fkrit)*sqrt((1/n1+1/n2)*Sp[i,i])
    print(paste0(round(lower,3)," <<>> ",round(upper,3)))
}
```


#repetisi
```{r}
n <- 100
p <- 4
ybar <- c(3.23,3.22,3.13,3.11)
D <- diag(c(0.251,0.149,0.254,0.141)) #ini deviasi
R <- matrix(c(1,0.750,0.727,0.588,0.750,1,0.629,0.05,0.727,0.629,1,0.684,0.588,0.05,0.684,1),4,4,byrow=TRUE)
C <- matrix(c(1,1,-1,-1,1,-1,1,-1,1,-1,-1,1),3,4,byrow=TRUE)
Cbar <- C%*%ybar
S = D%*%R%*%D
CSC <- C%*%S%*%t(C)
T2 <- n*t(Cbar)%*%solve(CSC)%*%Cbar
T2
Fkrit <- ((n-1)*(p-1))/(n-p+1)*qf(0.95,p-1,n-p)
Fkrit
```

```{r}
for(i in 1:p){
  lower <- ybar[i]-(sqrt(((n-1)*p)/(n-p)*qf(0.95,p,n-p))*sqrt(S[i,i]/n))
    upper <- ybar[i]+sqrt(((n-1)*p)/(n-p)*qf(0.95,p,n-p))*sqrt(S[i,i]/n)
    print(paste0(round(lower,3)," <<>> ",round(upper,3)))
}
```


#2020/2021 independent
```{r}
getCov <- function(std, cor) {
 diag(std) %*% cor %*% diag(std)
}
```

```{r}
p <- 6
alpha <- 0.05
laki.n <- 20
laki.xbar <- c(124.50, 38.10, 76.20, 192.75, 53.65, 250.3)
laki.std <- sqrt(c(384.3, 68.2, 121.1, 1000.2, 322.4, 470.2))
data <- c(1, 0.13, 0.38, 0.04, -0.05, 0.2,
 0.13, 1, 0.11, 0.1, -0.43, 0.04,
 0.38, 0.11, 1, -0.11, 0, -0.02, 
 0.04, 0.1, -0.11, 1, -0.04, -0.01,
 -0.05, -0.43, 0, -0.04, 1, -0.34,
 0.2, 0.04, -0.02, -0.01, -0.34, 1)
laki.cor <- matrix(data, ncol= 6)
laki.cov <- getCov(laki.std, laki.cor)
laki.cov 
```

```{r}
perempuan.n <- 20
perempuan.xbar <- c(129.30, 31.70, 87.40, 236.60, 44.25, 280.20)
perempuan.std <- sqrt(c(687.8, 51.7, 110.9, 792.6, 173.7,1253.7))
data <- c(1, 0.37, -0.19, 0.1, 0, 0.47,
 0.37, 1, 0.04, -0.23, -0.37, 0.22,
 -0.19, 0.04, 1, 0.15, -0.06, -0.3,
 0.1, -0.23, 0.15, 1, 0.02, 0.13,
 0, -0.37, -0.06, 0.02, 1, 0.25,
 0.47, 0.22, -0.3, 0.13, 0.25, 1)
perempuan.cor <- matrix(data, ncol= 6)
perempuan.cov <- getCov(perempuan.std, perempuan.cor)
perempuan.cov 
```

```{r}
s_pool <- (1/(laki.n + perempuan.n - 2)) * (((laki.n-1)*laki.cov) + ((perempuan.n-1)*perempuan.cov))
T2 <- (laki.n * perempuan.n/(laki.n + perempuan.n))* (t(laki.xbar - perempuan.xbar) %*% solve(s_pool) %*% (laki.xbar - perempuan.xbar))
cat("Nilai statistik uji T^2\n", T2) 
nilai.F <- qf((1-alpha), p, laki.n + perempuan.n - p - 1)
c2 <- (((laki.n + perempuan.n - 2)/(laki.n + perempuan.n - p - 1) * p)) * nilai.F
cat("\n\nNilai c^2\n", c2)
```

```{r}
if(T2>c2){
 cat("\n\nKeputusan: Tolak H0")
} else {
 cat("\n\nKeputusan: Gagal Tolak H0")
} 
```

```{r}
newAlpha <- alpha / (2*p)
xbar <- laki.xbar - perempuan.xbar
a <- c(0, 0, 0, 0, 1, 0)
n <- laki.n + perempuan.n - 2
as.numeric(t(a) %*% xbar) + c(-1, 1) * qt(1 - newAlpha, n -1) * sqrt(as.numeric(t(a) %*% s_pool %*% a) / n) 
```
```{r}
newAlpha <- alpha / (2*p)
xbar <- perempuan.xbar - laki.xbar
a <- c(0, 0, 0, 0, 0, 1)
n <- laki.n + perempuan.n - 2
as.numeric(t(a) %*% xbar) + c(-1, 1) * qt(1 - newAlpha, n -1) * sqrt(as.numeric(t(a) %*% s_pool %*% a) / n) 
```


#2021/2022 Berpasangan
```{r}
n <- 20
mu <- 0
p <- 3
df2 <- n - p
xbar1 <- c(400.75,102.05,213.05)
xbar2 <- c(356.7,200.4,254.7)
xbar <- c(-44.05,98.35,41.65)
S1 <- matrix(c(911.88,164.54,371.33,164.54,128.89,147.94,371.33,147.94,551.94),3,3,byrow=TRUE)
S2 <- matrix(c(748.64,175.86,32.59,175.86,245.62,95.65,32.59,95.65,273.8),3,3,byrow=TRUE)
S <- matrix(c(1748.89,218.91,718.67,218.91,321.92,345.23,718.67,345.23,1216.77),3,3,byrow=TRUE)
T2 <- n * t(xbar - mu) %*% solve(S) %*% (xbar - mu)
  Fstat <- T2 / (p * (n-1) / df2)
  pval <- 1 - pf(Fstat, df1=p, df2=df2)
  for(i in 1:p){
    bonf_low <- xbar[i] - qt(1-(0.05/(2*p)),n-1) * sqrt(S[i,i]/n)
  bonf_upp <- xbar[i] + qt(1-(0.05/(2*p)),n-1) * sqrt(S[i,i]/n)
  print(paste(bonf_low," ",bonf_upp))
  }
  
  data.frame(T2=as.numeric(T2), Fstat=as.numeric(Fstat),
  df1=p, df2=df2, p.value=as.numeric(pval), row.names="")
```

#2021/2022
```{r}
n1 <- 30
n2 <- 20
p <- 3
xbar1 <- c(80.05,85.06,89.99)
xbar2 <- c(81.05,83.03,89.96)
D1 <- diag(c(0.176,0.17,0.247))
R1 <- matrix(c(1,0.82,0.06,0.82,1,-0.02,0.06,-0.02,1),3,3,byrow=TRUE)
S1 <- D1%*%R1%*%D1
D2 <- diag(c(0.157,0.157,0.213))
R2 <- matrix(c(1,0.74,0.43,0.74,1,0.24,0.43,0.24,1),3,3,byrow=TRUE)
S2 <- D2%*%R2%*%D2
Sp <- (n1-1)/(n1+n2-2)*S1 + (n2-1)/(n1+n2-2)*S2
T2 <- (n1*n2/(n1+n2))*t(xbar1-xbar2)%*%solve(Sp)%*%(xbar1-xbar2)
Fkrit <- p*(n1+n2-2)/(n1+n2-p-1)*qf(0.95,p,n1+n2-p-1)
```

```{r}
for(i in 1:p){
  low <- (xbar1[i]-xbar2[i])-sqrt(Fkrit)*sqrt((1/n1+1/n2)*Sp[i,i])
  up <- (xbar1[i]-xbar2[i])+sqrt(Fkrit)*sqrt((1/n1+1/n2)*Sp[i,i])
  print(paste(low," ",up))
}
```


